### ISSUE TITLE
Replace JSON with MessagePack as Polyfony\Cache storage engine

### ISSUE THREAD

**Issue by AnnoyingTechnology** [sib-retail/polyfony#112]
It's much more efficient, twice as fast actually

**Comment by AnnoyingTechnology** [comment]
Nope... Non human readable cache file... so...

**Comment by AnnoyingTechnology** [comment]
@WarenN ça te gênerait que les fichiers de cache du framework ne soient pas lisible directement ?
càd pas pouvoir faire un `cat Private/Storage/Cache/Includes`
par exemple, mais devoir utiliser une commande genre `msgpack-cli decode Private/Storage/Cache/Includes` ? 
On peut gagner en perf en fait

**Comment by WarenN** [comment]
@AnnoyingTechnology Non ça ne me gênerais pas, de toute façon, on est pas cencé y accéder.

**Comment by AnnoyingTechnology** [comment]
ouai, mais il arrive que tu te dises, merde, pourquoi ce truc fonctionne pas (en prod), et de faire un cat sur un fichier de cache pour vérifier si la conf est bonne par exemple. En tout cas ça m'arrive.

**Comment by WarenN** [comment]
moi aussi ça m'est arrivé, mais si tu n'es pas sûr de la config en cache, tu effaces le cache avant de tenter de trouver ce qui va pas en déchiffrant le JSON. Au pire si on peut décoder le pack et jetter un coup d'oeil, c'est bon.

**Comment by AnnoyingTechnology** [comment]
ok ça marche
