### ISSUE TITLE
Polyfony\Store\Cookies::put() : bug $lifetime

### ISSUE THREAD

**Issue by WarenN** [sib-retail/polyfony#121]
Si la valeur optionnelle $lifetime n'est pas renseignée, le cookie n'est pas pris en compte compte tenu que la durée de vie par défaut du cookie n'est pas ajouté au timestamp actuel :

$lifetime = $lifetime ? time() + $lifetime * 3600 : 24 * 3600;

**Comment by AnnoyingTechnology** [comment]
propose un fix stp

**Comment by AnnoyingTechnology** [comment]
pas de fix ?

**Comment by AnnoyingTechnology** [comment]
Fix le !

**Comment by AnnoyingTechnology** [comment]
(Il faut préciser Fix #121 dans le commit qui corrige)

Fixed in https://github.com/sib-retail/polyfony/commit/e14eab40433cebc62fae2f25f31cf9ce4062eec9
