### ISSUE TITLE
Option de Dev

### ISSUE THREAD

**Issue by WarenN** [sib-retail/polyfony#78]
Peut être serait-il interessant de permettre un retour d'infos de débogage de type json :

pf\Response::setType('json');
pf\Response::setContent( array(
    'debug' => array('query' => $query, '...' => '...'),
    'result' => 'ok'
    ));

Qui serait automatiquement supprimé en mode Prod

**Comment by AnnoyingTechnology** [comment]
maybe… Le profiler s'injecte automatiquement dans le retour JSON il me
semble, donc ça ne doit pas être grand chose à ajouter 

---

Julien

On 2015-04-21 15:07, WarenN wrote: 

> Peut être serait-il interessant de permettre un retour d'infos de débogage de type json : 
> 
> pfResponse::setType('json');
> pfResponse::setContent( array(
> 'debug' => array('query' => $query, '...' => '...'),
> 'result' => 'ok'
> )); 
> 
> Qui serait automatiquement supprimé en mode Prod 
> 
> --
> Reply to this email directly or view it on GitHub [1].
 

Links:
------
[1] https://github.com/SIB-FRANCE/Polyfony2/issues/78

**Comment by AnnoyingTechnology** [comment]
déjà apporté par le Profiler()
